## Łączenie z bazą danych przy pomocy skryptu Python

Istnieje wiele bibliotek do obsługi połączeń Pythona z bazami danych. Na tych zajęciach będziemy korzystać z biblioteki sqlAlchemy oraz psycopg2. 

### Instalacja niezbędnych pakietów
```

pip install sqlalchemy psycopg2-binary pandas

```

### Łączenie się za pomocą sqlAlchemy
```python

from sqlalchemy import create_engine

db_string = "postgres://postgres:admin@localhost:5432/test"

db = create_engine(db_string)

connection_sqlalchemy = db.connect()

```

Gdzie *db_string* formatowany jest w następujący sposób:

nazwa_silnika://użytkownik:hasło@adres_serwera:port/nazwa_bazy

Zapytanie do bazy danych wraz z przeglądnięciem wyników można wykonać używając skryptu:
```python

result_set = db.execute("SELECT * FROM city")  
for r in result_set:  
    print(r)

```
Fragment wyniku:
```

(1, 'A Corua (La Corua)', 87, datetime.datetime(2006, 2, 15, 9, 45, 25))
(2, 'Abha', 82, datetime.datetime(2006, 2, 15, 9, 45, 25))
(3, 'Abu Dhabi', 101, datetime.datetime(2006, 2, 15, 9, 45, 25))
...

```
Stosując tą metodę wynik zapytania do zmiennej *result_set* jest zwracany jako obiekt typu [ResultProxy](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.ResultProxy).
### Łączenie się za pomocą psycopg2 i pandas
```python
import psycopg2 as pg
import pandas as pd

connection = pg.connect(host='localhost', port=5432, dbname='test', user='postgres', password='admin')
```

Wykonanie zapytania:
```python
df = pd.read_sql('select * from city',con=connection)
print(df)
```

Rezultat:

|     	| city_id 	|               city 	| country_id 	|         last_update 	|
|----:	|--------:	|-------------------:	|-----------:	|--------------------:	|
|   0 	|       1 	| A Corua (La Corua) 	|         87 	| 2006-02-15 09:45:25 	|
|   1 	|       2 	|               Abha 	|         82 	| 2006-02-15 09:45:25 	|
|   2 	|       3 	|          Abu Dhabi 	|        101 	| 2006-02-15 09:45:25 	|
|   3 	|       4 	|               Acua 	|         60 	| 2006-02-15 09:45:25 	|
|   4 	|       5 	|              Adana 	|         97 	| 2006-02-15 09:45:25 	|
| ... 	|     ... 	|                ... 	|        ... 	|                 ... 	|

W tym przypadku wyniki zapisywany jest w postaci obiektu [DataFeram](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html?highlight=dataframe#pandas.DataFrame) z biblioteki [pandas](https://pandas.pydata.org).

Dodatkowo możliwe jest użycie pandasa i sqlAlchemy, przykład użycia tego mechanizmu znajduje się w notatniku example.

## Baza ćwiczeniowa

W części poświęconej bazom danych na zajęciach będziemy używać bazy z oficjalnego tutorialu PostgeSQL dostępnej [tutaj](https://www.postgresqltutorial.com/postgresql-sample-database/).

## Dane do połączenia do bazy zdalnej
	- host: pgsql-196447.vipserv.org
	- port: 5432
	- login: wbauer_adb_2023
	- hasło: adb2020
	- nazwa_bazy: wbauer_adb

## Przykładowe tabele obrazujące łączenie

Do zobrazowania operacji łączenia zostaną użyte tabele:

```sql
CREATE TABLE shape_a (
    id INT PRIMARY KEY,
    shape VARCHAR (100) NOT NULL
);
 
CREATE TABLE shape_b (
    id INT PRIMARY KEY,
    shape VARCHAR (100) NOT NULL
);
```
 
Polecenie CREATE TABLE tworzy tabelę o zadanej nazwie i strukturze. Ogólna postać to:
```sql
CREATE TABLE tab_name (
    col_name1 data_type constrain,
    col_name1 data_type constrain,
    ...
);
```
Należy uzupełnić ją danymi:
```sql
INSERT INTO shape_a (id, shape)
VALUES
    (1, 'Trójkąt'),
    (2, 'Kwadrat'),
    (3, 'Deltoid'),
    (4, 'Traper');
 
INSERT INTO shape_b (id, shape)
VALUES
    (1, 'Kwadrat'),
    (2, 'Trójkąt'),
    (3, 'Romb'),
    (4, 'Równoległobok');
```
Komenda INSERT INTO pozwala na dodanie do tabeli rekordów. Ogólna postać to:

```sql
INSERT INTO tab_name (col1_name, col2_name2, ...) 
VALUES
    (val1_col1, val2_col2),
    (val2_col1, val2_col2),
    ...
```

## Inner join 

Jest to podstawowy rodzaj złączenie. Ten sposób złączenia wybiera  te wiersze, dla których warunek złączenia jest spełniony. W żadnej z łączonych tabel kolumna użyta do łączenia nie może mieć wartości NULL. 

#### Przykład:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
INNER JOIN shape_b b ON a.shape = b.shape;
```
W zapytaniu powyżej użyto *aliasów* nazw tabel i column wynikowych, jest to szczególnie przydatne przy długich nazwach tabel i wprowadza czytelność w zapytaniu.

#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Trójkąt|2|Trójkąt|
|2|Kwadrat|1|Kwadrat|

## OUTER JOIN

Istnieją trzy rodzaje złączeń OUTER:
- LEFT OUTER JOIN,
- RIGHT OUTER JOIN,
- FULL OUTER JOIN.

### LEFT OUTER JOIN

Ten rodzaj złączenie zwróci wszystkie rekordy z lewej tablicy i dopasuje do nich rekordy z prawej tablicy które spełniją zadany warunek złączenia. Jeżeli w prawej tablicy nie występują rekordy spełnijące warunek złączenia z lewą w ich miejscu pojawią się wartości NULL.

#### Przykład 1:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
LEFT JOIN shape_b b ON a.shape = b.shape;
```
#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Trójkąt|2|Trójkąt|
|2|Kwadrat|1|Kwadrat|
|3|Deltoid|NULL|NULL|
|4|Traper|NULL|NULL|

#### Przykład 2:
```sql
SELECT
    b.id id_b,
    b.shape shape_b,
    a.id id_a,
    a.shape shape_a   
FROM
    shape_b b
LEFT JOIN shape_a a ON a.shape = b.shape;
```
#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Kwadrat|2|Kwadrat|
|2|Trójkąt|1|Trójkąt|
|3|Romb|NULL|NULL|
|4|Równoległobok|NULL|NULL|

### RIGHT OUTER JOIN

Działa jak left outer join z tym, że prawa tablica w zapytaniu jest brana w całości.

#### Przykład:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
RIGHT JOIN shape_b b ON a.shape = b.shape;
```

#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|2|Kwadrat|1|Kwadrat|
|1|Trójkąt|2|Trójkąt|
|NULL|NULL|3|Romb|
|NULL|NULL|4|Równoległobok|


### FULL OUTER JOIN

Jest złączeniem które zwraca:
- wiersze dla których warunek złączenia jest spełniony,
- wiersze z lewej tabeli dla których nie ma odpowiedników w prawej,
- wiersze z prawej tabeli dla których nie ma odpowiedników w lewej. 

#### Przykład:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
FULL JOIN shape_b b ON a.shape = b.shape;
```
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Trójkąt|2|Trójkąt|
|2|Kwadrat|1|Kwadrat|
|3|Deltoid"|NULL|NULL|
|4|Traper|NULL|NULL|
|NULL|NULL|3|Romb|
|NULL|NULL|4|Równoległobok|

## Zadania wprowadzające
Wykonaj zapytania przy użyciu DBMS:  
  
1. Wyświetl imię, nazwisko i datę wypożyczenia klientów.
2. Wyświetl wszystkie filmy oraz ich kategorię.
3. Znajdź listę wszystkich filmów o tej samej długości.
4. Znajdź wszystkich klientów mieszkających w tym samym mieście.
5. Wyświetl wszystkich aktorów grających w filmie "ACADEMY DINOSAUR".
6. Porównaj: INNER JOIN z LEFT JOIN dla tabel customer i rental.
7. Znajdź klientów, którzy nigdy nie wypożyczyli filmu.
8. Wyświetl wszystkie wypożyczenia wraz z tytułem filmu.
9. Porównaj wydajność: INNER JOIN LEFT JOIN dla tego samego zapytania
10. Uruchom zapytania: w pgAdmin i w Pythonie, zmierz czas wykonania (np. time w Pythonie) porównaj: czas i  wygodę pracy
11. Uzupełnij funkcje z pliku `main.py` tak by przechodziła testy w pytest

In [21]:
import sqlalchemy
from sqlalchemy import create_engine, text
import pandas as pd

connector = "postgresql"
user = "postgres"
password = "9731"
host = "localhost"
port = "5432"
dbname = "dvdrental"

db_string = f"{connector}://{user}:{password}@{host}:{port}/{dbname}"
db = create_engine(db_string)
connection_sqlalchemy = db.connect()

In [22]:
command = 'select * from city'
df = pd.read_sql(command, con=connection_sqlalchemy)
df

     city_id                city  country_id         last_update
0          1  A Corua (La Corua)          87 2006-02-15 09:45:25
1          2                Abha          82 2006-02-15 09:45:25
2          3           Abu Dhabi         101 2006-02-15 09:45:25
3          4                Acua          60 2006-02-15 09:45:25
4          5               Adana          97 2006-02-15 09:45:25
..       ...                 ...         ...                 ...
595      596               Zaria          69 2006-02-15 09:45:25
596      597        Zeleznogorsk          80 2006-02-15 09:45:25
597      598         Zhezqazghan          51 2006-02-15 09:45:25
598      599            Zhoushan          23 2006-02-15 09:45:25
599      600          Ziguinchor          83 2006-02-15 09:45:25

[600 rows x 4 columns]

In [27]:
# INSPEKTOR DO ZNAJDOWANIA NAZW
from sqlalchemy import inspect
inspector = inspect(db)
tables = inspector.get_table_names()
tables

['actor',
 'store',
 'address',
 'category',
 'city',
 'country',
 'customer',
 'film_actor',
 'film_category',
 'inventory',
 'language',
 'rental',
 'staff',
 'payment',
 'film']

In [36]:
columns = inspector.get_columns('category')
columns = inspector.get_columns('film_category')
columns = inspector.get_columns('film')
col_names = [col['name'] for col in columns]
col_names

['film_id',
 'title',
 'description',
 'release_year',
 'language_id',
 'rental_duration',
 'rental_rate',
 'length',
 'replacement_cost',
 'rating',
 'last_update',
 'special_features',
 'fulltext']

ZADANIE 1

In [ ]:
command = text("""
select first_name, last_name from customer""")
df = pd.read_sql(command, con=connection_sqlalchemy)
df

    first_name  last_name
0        Jared        Ely
1         Mary      Smith
2     Patricia    Johnson
3        Linda   Williams
4      Barbara      Jones
..         ...        ...
594   Terrence  Gunderson
595    Enrique   Forsythe
596    Freddie     Duggan
597       Wade   Delvalle
598     Austin    Cintron

[599 rows x 2 columns]

ZADANIE 2

ZADANIE 2

ZADANIE 2

In [38]:
import main
from main import film_in_category, client_from_city, actor_in_film

result = film_in_category(2)
display(result)

/home/majk/Documents/Coding/academic_coding/BazyDanych/lab_3_join-main/main.py:49: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(command, con=connection)

DatabaseError: Execution failed on sql '
    --sql
    select title, language, category from ... SORT BY title, language
    ': syntax error at or near ".."
LINE 3:     select title, language, category from ... SORT BY title,...
                                                  ^