## Łączenie z bazą danych przy pomocy skryptu Python

Istnieje wiele bibliotek do obsługi połączeń Pythona z bazami danych. Na tych zajęciach będziemy korzystać z biblioteki sqlAlchemy oraz psycopg2. 

### Instalacja niezbędnych pakietów
```

pip install sqlalchemy psycopg2-binary pandas

```

### Łączenie się za pomocą sqlAlchemy
```python

from sqlalchemy import create_engine

db_string = "postgres://postgres:admin@localhost:5432/test"

db = create_engine(db_string)

connection_sqlalchemy = db.connect()

```

Gdzie *db_string* formatowany jest w następujący sposób:

nazwa_silnika://użytkownik:hasło@adres_serwera:port/nazwa_bazy

Zapytanie do bazy danych wraz z przeglądnięciem wyników można wykonać używając skryptu:
```python

result_set = db.execute("SELECT * FROM city")  
for r in result_set:  
    print(r)

```
Fragment wyniku:
```

(1, 'A Corua (La Corua)', 87, datetime.datetime(2006, 2, 15, 9, 45, 25))
(2, 'Abha', 82, datetime.datetime(2006, 2, 15, 9, 45, 25))
(3, 'Abu Dhabi', 101, datetime.datetime(2006, 2, 15, 9, 45, 25))
...

```
Stosując tą metodę wynik zapytania do zmiennej *result_set* jest zwracany jako obiekt typu [ResultProxy](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.ResultProxy).
### Łączenie się za pomocą psycopg2 i pandas
```python
import psycopg2 as pg
import pandas as pd

connection = pg.connect(host='localhost', port=5432, dbname='test', user='postgres', password='admin')
```

Wykonanie zapytania:
```python
df = pd.read_sql('select * from city',con=connection)
print(df)
```

Rezultat:

|     	| city_id 	|               city 	| country_id 	|         last_update 	|
|----:	|--------:	|-------------------:	|-----------:	|--------------------:	|
|   0 	|       1 	| A Corua (La Corua) 	|         87 	| 2006-02-15 09:45:25 	|
|   1 	|       2 	|               Abha 	|         82 	| 2006-02-15 09:45:25 	|
|   2 	|       3 	|          Abu Dhabi 	|        101 	| 2006-02-15 09:45:25 	|
|   3 	|       4 	|               Acua 	|         60 	| 2006-02-15 09:45:25 	|
|   4 	|       5 	|              Adana 	|         97 	| 2006-02-15 09:45:25 	|
| ... 	|     ... 	|                ... 	|        ... 	|                 ... 	|

W tym przypadku wyniki zapisywany jest w postaci obiektu [DataFeram](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html?highlight=dataframe#pandas.DataFrame) z biblioteki [pandas](https://pandas.pydata.org).

Dodatkowo możliwe jest użycie pandasa i sqlAlchemy, przykład użycia tego mechanizmu znajduje się w notatniku example.

## Baza ćwiczeniowa

W części poświęconej bazom danych na zajęciach będziemy używać bazy z oficjalnego tutorialu PostgeSQL dostępnej [tutaj](https://www.postgresqltutorial.com/postgresql-sample-database/).

## Dane do połączenia do bazy zdalnej
	- host: pgsql-196447.vipserv.org
	- port: 5432
	- login: wbauer_adb_2023
	- hasło: adb2020
	- nazwa_bazy: wbauer_adb

## Przykładowe tabele obrazujące łączenie

Do zobrazowania operacji łączenia zostaną użyte tabele:

```sql
CREATE TABLE shape_a (
    id INT PRIMARY KEY,
    shape VARCHAR (100) NOT NULL
);
 
CREATE TABLE shape_b (
    id INT PRIMARY KEY,
    shape VARCHAR (100) NOT NULL
);
```
 
Polecenie CREATE TABLE tworzy tabelę o zadanej nazwie i strukturze. Ogólna postać to:
```sql
CREATE TABLE tab_name (
    col_name1 data_type constrain,
    col_name1 data_type constrain,
    ...
);
```
Należy uzupełnić ją danymi:
```sql
INSERT INTO shape_a (id, shape)
VALUES
    (1, 'Trójkąt'),
    (2, 'Kwadrat'),
    (3, 'Deltoid'),
    (4, 'Traper');
 
INSERT INTO shape_b (id, shape)
VALUES
    (1, 'Kwadrat'),
    (2, 'Trójkąt'),
    (3, 'Romb'),
    (4, 'Równoległobok');
```
Komenda INSERT INTO pozwala na dodanie do tabeli rekordów. Ogólna postać to:

```sql
INSERT INTO tab_name (col1_name, col2_name2, ...) 
VALUES
    (val1_col1, val2_col2),
    (val2_col1, val2_col2),
    ...
```

## Inner join 

Jest to podstawowy rodzaj złączenie. Ten sposób złączenia wybiera  te wiersze, dla których warunek złączenia jest spełniony. W żadnej z łączonych tabel kolumna użyta do łączenia nie może mieć wartości NULL. 

#### Przykład:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
INNER JOIN shape_b b ON a.shape = b.shape;
```
W zapytaniu powyżej użyto *aliasów* nazw tabel i column wynikowych, jest to szczególnie przydatne przy długich nazwach tabel i wprowadza czytelność w zapytaniu.

#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Trójkąt|2|Trójkąt|
|2|Kwadrat|1|Kwadrat|

## OUTER JOIN

Istnieją trzy rodzaje złączeń OUTER:
- LEFT OUTER JOIN,
- RIGHT OUTER JOIN,
- FULL OUTER JOIN.

### LEFT OUTER JOIN

Ten rodzaj złączenie zwróci wszystkie rekordy z lewej tablicy i dopasuje do nich rekordy z prawej tablicy które spełniją zadany warunek złączenia. Jeżeli w prawej tablicy nie występują rekordy spełnijące warunek złączenia z lewą w ich miejscu pojawią się wartości NULL.

#### Przykład 1:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
LEFT JOIN shape_b b ON a.shape = b.shape;
```
#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Trójkąt|2|Trójkąt|
|2|Kwadrat|1|Kwadrat|
|3|Deltoid|NULL|NULL|
|4|Traper|NULL|NULL|

#### Przykład 2:
```sql
SELECT
    b.id id_b,
    b.shape shape_b,
    a.id id_a,
    a.shape shape_a   
FROM
    shape_b b
LEFT JOIN shape_a a ON a.shape = b.shape;
```
#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Kwadrat|2|Kwadrat|
|2|Trójkąt|1|Trójkąt|
|3|Romb|NULL|NULL|
|4|Równoległobok|NULL|NULL|

### RIGHT OUTER JOIN

Działa jak left outer join z tym, że prawa tablica w zapytaniu jest brana w całości.

#### Przykład:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
RIGHT JOIN shape_b b ON a.shape = b.shape;
```

#### Wynik:
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|2|Kwadrat|1|Kwadrat|
|1|Trójkąt|2|Trójkąt|
|NULL|NULL|3|Romb|
|NULL|NULL|4|Równoległobok|


### FULL OUTER JOIN

Jest złączeniem które zwraca:
- wiersze dla których warunek złączenia jest spełniony,
- wiersze z lewej tabeli dla których nie ma odpowiedników w prawej,
- wiersze z prawej tabeli dla których nie ma odpowiedników w lewej. 

#### Przykład:
```sql
SELECT
    a.id id_a,
    a.shape shape_a,
    b.id id_b,
    b.shape shape_b
FROM
    shape_a a
FULL JOIN shape_b b ON a.shape = b.shape;
```
|id_a|shape_a|id_b|shape_b|
|-|-|-|-|
|1|Trójkąt|2|Trójkąt|
|2|Kwadrat|1|Kwadrat|
|3|Deltoid"|NULL|NULL|
|4|Traper|NULL|NULL|
|NULL|NULL|3|Romb|
|NULL|NULL|4|Równoległobok|

## Zadania wprowadzające
Wykonaj zapytania przy użyciu DBMS:  
  
1. Wyświetl imię, nazwisko i datę wypożyczenia klientów.
2. Wyświetl wszystkie filmy oraz ich kategorię.
3. Znajdź listę wszystkich filmów o tej samej długości.
4. Znajdź wszystkich klientów mieszkających w tym samym mieście.
5. Wyświetl wszystkich aktorów grających w filmie "ACADEMY DINOSAUR".
6. Porównaj: INNER JOIN z LEFT JOIN dla tabel customer i rental.
7. Znajdź klientów, którzy nigdy nie wypożyczyli filmu.
8. Wyświetl wszystkie wypożyczenia wraz z tytułem filmu.
9. Porównaj wydajność: INNER JOIN LEFT JOIN dla tego samego zapytania
10. Uruchom zapytania: w pgAdmin i w Pythonie, zmierz czas wykonania (np. time w Pythonie) porównaj: czas i  wygodę pracy
11. Uzupełnij funkcje z pliku `main.py` tak by przechodziła testy w pytest

In [1]:
import sqlalchemy
from sqlalchemy import create_engine, text
import pandas as pd

connector = "postgresql"
user = "postgres"
password = "9731"
host = "localhost"
port = "5432"
dbname = "dvdrental"

db_string = f"{connector}://{user}:{password}@{host}:{port}/{dbname}"
db = create_engine(db_string)
connection_sqlalchemy = db.connect()

ZADANIE 1

In [2]:
command = text("""--sql
SELECT c.first_name AS name, c.last_name AS surname, p.payment_date as rental_date
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
ORDER BY c.last_name, c.first_name, p.payment_date
""")
df = pd.read_sql(command, con=connection_sqlalchemy)
df

          name surname                rental_date
0       Rafael   Abney 2007-02-16 18:45:46.996577
1       Rafael   Abney 2007-02-17 02:04:28.996577
2       Rafael   Abney 2007-02-19 16:32:44.996577
3       Rafael   Abney 2007-02-20 18:09:54.996577
4       Rafael   Abney 2007-03-01 23:47:59.996577
...        ...     ...                        ...
14591  Cynthia   Young 2007-04-30 00:13:17.996577
14592  Cynthia   Young 2007-04-30 01:50:56.996577
14593  Cynthia   Young 2007-04-30 06:08:59.996577
14594  Cynthia   Young 2007-04-30 19:42:28.996577
14595  Cynthia   Young 2007-05-14 13:44:29.996577

[14596 rows x 3 columns]

ZADANIE 2

In [3]:
command = text("""--sql
SELECT f.title, c.name AS category 
        FROM film f
        JOIN language l ON f.language_id = l.language_id
        JOIN film_category fc ON f.film_id = fc.film_id
        JOIN category c ON fc.category_id = c.category_id
        ORDER BY f.title, l.name
""")
df = pd.read_sql(command, con=connection_sqlalchemy)
df

                 title     category
0     Academy Dinosaur  Documentary
1       Ace Goldfinger       Horror
2     Adaptation Holes  Documentary
3     Affair Prejudice       Horror
4          African Egg       Family
..                 ...          ...
995     Young Language  Documentary
996         Youth Kick        Music
997       Zhivago Core       Horror
998  Zoolander Fiction     Children
999          Zorro Ark       Comedy

[1000 rows x 2 columns]

ZADANIE 3

In [4]:
command = text("""--sql
               SELECT title, length AS film_len
               FROM film
               WHERE length = 60
""")
df = pd.read_sql(command, con=connection_sqlalchemy)
df

                   title  film_len
0          Bubble Grosse        60
1           Jersey Sassy        60
2  Mockingbird Hollywood        60
3          Phantom Glory        60
4             Pity Bound        60
5             Room Roman        60
6     Shakespeare Saddle        60
7          Smile Earring        60

ZADANIE 4

In [5]:
with db.connect() as conn:
    command = text("""--sql
        SELECT 
            c.city as city, 
            cus.first_name as first_name, 
            cus.last_name as last_name 
        FROM customer cus
        JOIN address adr ON cus.address_id = adr.address_id
        JOIN city c ON adr.city_id = c.city_id
        WHERE c.city = :city
        ORDER BY last_name, first_name
    """)
    df = pd.read_sql(command, con=conn, params={"city": "Manchester"})

df

         city first_name last_name
0  Manchester     Victor   Barkley

ZADANIE 5

In [8]:
with db.connect() as conn:
    command = text("""--sql
                   SELECT f.title AS title, act.first_name AS name, act.last_name AS surname
                   FROM actor act
                   JOIN film_actor fact ON act.actor_id = fact.actor_id
                   JOIN film f ON fact.film_id = f.film_id
                   WHERE f.title = 'Academy Dinosaur'
    """)
    df = pd.read_sql(command, con=conn)

df

              title       name  surname
0  Academy Dinosaur   Penelope  Guiness
1  Academy Dinosaur  Christian    Gable
2  Academy Dinosaur    Lucille    Tracy
3  Academy Dinosaur     Sandra     Peck
4  Academy Dinosaur     Johnny     Cage
5  Academy Dinosaur       Mena   Temple
6  Academy Dinosaur     Warren    Nolte
7  Academy Dinosaur      Oprah   Kilmer
8  Academy Dinosaur       Rock  Dukakis
9  Academy Dinosaur       Mary   Keitel

ZADANIE 6

In [ ]:
with db.connect() as conn:
    command = text("""--sql
                   SELECT f.title AS title, act.first_name AS name, act.last_name AS surname
                   FROM actor act
                   JOIN film_actor fact ON act.actor_id = fact.actor_id
                   JOIN film f ON fact.film_id = f.film_id
                   WHERE f.title = 'Academy Dinosaur'
    """)
    df = pd.read_sql(command, con=conn)

df

ZADANIE 3

ZADANIE 3

ZADANIE 3

ZADANIE 3

# ZADANIA Z MAIN

In [ ]:
import main
from main import film_in_category, client_from_city, actor_in_film, film_in_language

result = film_in_category(3)
display(result)

                   title              language  category
0    Backlash Undefeated  English               Children
1         Bear Graceland  English               Children
2           Beneath Rush  English               Children
3          Betrayed Rear  English               Children
4            Cabin Flash  English               Children
5       Casper Dragonfly  English               Children
6    Christmas Moonshine  English               Children
7           Circus Youth  English               Children
8     Clockwork Paradise  English               Children
9      Comancheros Enemy  English               Children
10       Crooked Frogmen  English               Children
11      Daughter Madigan  English               Children
12          Doctor Grail  English               Children
13      Empire Malkovich  English               Children
14          Fargo Gandhi  English               Children
15     Forever Candidate  English               Children
16       Full Flatliners  English               Children
17           Fury Murder  English               Children
18       Ghost Groundhog  English               Children
19        Giant Troopers  English               Children
20        Gorgeous Bingo  English               Children
21         Graduate Lord  English               Children
22          Hall Cassidy  English               Children
23  Heartbreakers Bright  English               Children
24   Hollywood Anonymous  English               Children
25    Holocaust Highball  English               Children
26       Idols Snatchers  English               Children
27      Invasion Cyclone  English               Children
28          Jersey Sassy  English               Children
29         Jumping Wrath  English               Children
30      Labyrinth League  English               Children
31       Language Cowboy  English               Children
32     Legally Secretary  English               Children
33        Magic Mallrats  English               Children
34          Maker Gables  English               Children
35  Microcosmos Paradise  English               Children
36            Model Fish  English               Children
37      Murder Antitrust  English               Children
38             Noon Papi  English               Children
39       Polish Brooklyn  English               Children
40          Robbers Joon  English               Children
41      Sabrina Midnight  English               Children
42           Santa Paris  English               Children
43         Scarface Bang  English               Children
44    Shepherd Midsummer  English               Children
45         Sister Freddy  English               Children
46       Splendor Patton  English               Children
47    Strangelove Desire  English               Children
48    Stranger Strangers  English               Children
49     Sundance Invasion  English               Children
50  Sweethearts Suspects  English               Children
51          Tequila Past  English               Children
52           Ties Hunger  English               Children
53         Tootsie Pilot  English               Children
54       Twisted Pirates  English               Children
55          Uptown Young  English               Children
56          Walls Artist  English               Children
57      Warlock Werewolf  English               Children
58        Wrong Behavior  English               Children
59     Zoolander Fiction  English               Children

In [ ]:
result = client_from_city('Manchester')
display(result)

         city first_name last_name
0  Manchester     Victor   Barkley

In [ ]:
result = actor_in_film("Backlash Undefeated")
display(result)

                 title         name  surname
0  Backlash Undefeated    Christian   Akroyd
1  Backlash Undefeated  Christopher    Berry
2  Backlash Undefeated    Sylvester     Dern
3  Backlash Undefeated        Kevin  Garland
4  Backlash Undefeated         Jane  Jackman
5  Backlash Undefeated      Spencer     Peck
6  Backlash Undefeated          Dan   Streep

In [ ]:
result = film_in_language("English")
display(result)

                 language              title
0    English                Academy Dinosaur
1    English                  Ace Goldfinger
2    English                Adaptation Holes
3    English                Affair Prejudice
4    English                     African Egg
..                    ...                ...
995  English                  Young Language
996  English                      Youth Kick
997  English                    Zhivago Core
998  English               Zoolander Fiction
999  English                       Zorro Ark

[1000 rows x 2 columns]